[package]
name = "foc-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
anyhow = "1.0"
lasso = "0.6.0"
itertools = "0.10.3"
rand = "0.8.5"
clap = { version = "3.1.12", features = ["derive"] }